### ISSUE TITLE
The watchdog sends mails when there are no messages

### ISSUE THREAD

**Issue by rengaw83** [DMKEBUSINESSGMBH/typo3-mklog#1]
i have a scheduler task, which runs every 5 minits:

| Config                                 | Value |
|----------------------------------------|-------|
| Minimum error level to trigger email.  | FATAL |
| Force a summary mail                   | No    |
| Include data_var.                      | Yes   |
| Group messages.                        | No    |

This task shoult send me a mail every 5 minits, if there are a new FATAL message.

But at the moment the scheduler sends a mail every 5 minits:

	This is an automatic email from TYPO3. Don't answer!
	
	Developer Log summary since 2015-08-10 09:20:05
	    Level INFO (Severity Number: 0): 18 items found
	
	Latest entries by log level
	
	Level FATAL (Severity Number: 0)
	
	Time: 1970-01-01 01:00:00
	Extension: 
	Message: 
	
	Count: 0 
	DataVar: 

It looks like a mail will always sent, when a entry of some level are stored.

A nother thing is, the messages looks grouped, but the option in the scheduler was set to false for the grouping.

**Comment by hannesbochmann** [comment]
The bug was fixed.
