### ISSUE TITLE
make extension compatible to TYPO3 7.6

### ISSUE THREAD

**Issue by hannesbochmann** [DMKEBUSINESSGMBH/typo3-mklog#2]

**Comment by digedag** [comment]
@hannesbochmann Warum liegt diese Klasse Tx_Rnbase_Utility_Extension_Devlog in rn_base? Wäre sie hier nicht besser aufgehoben?

**Comment by hannesbochmann** [comment]
Die wird z.B. auch in mklib benötigt und wollte die mklog und mklib nicht voneinander abhängig machen.

**Comment by digedag** [comment]
Mmh, finde ich irgendwie nicht so gut. Sollten wir nochmal besprechen... Laß es aber erstmal so! :smile:

**Comment by hannesbochmann** [comment]
Hat mir auch nicht so richtig gefallen, mir ist aber auf die schnelle keine bessere Lösung eingefallen. Wollte nicht extra eine eigene Extension dafür aufsetzen.

**Comment by digedag** [comment]
Vielleicht macht ja mklib da etwas, was eher in mklog gehört?

**Comment by hannesbochmann** [comment]
Reden wir drüber wenn wir uns wieder sehen.

**Comment by hannesbochmann** [comment]
Klasse wurde nach mklog verschoben.
