### ISSUE TITLE
Invalid default value for 'tx_mklog_lastrun'

### ISSUE THREAD

**Issue by dkochc** [DMKEBUSINESSGMBH/typo3-mklog#23]
https://github.com/DMKEBUSINESSGMBH/typo3-mklog/blob/dc6c6571131b1489cb946f1fc82bc83d6c22f194/ext_tables.sql#L5

Default value ''0000-00-00 00:00:00' is invalid in strict SQL mode. It must be replaced by '1970-01-01 00:00:00'.

**Comment by rengaw83** [comment]
This field can be dropped completely, it is not used anymore since version 10 ( https://github.com/DMKEBUSINESSGMBH/typo3-mklog/commit/17c35d9ad3c8a35a94414db75a58332e91968728 ).
