### ISSUE TITLE
SQL-Fehler nach Installation

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-mklog#4]
Nach der Installation in TYPO3 7.6 bekomme ich im BE-Modul folgende Fehlermeldung:

> SQL QUERY IS NOT VALID
> Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 't3_74.DEVLOGENTRY.uid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
> SELECT DEVLOGENTRY.\* FROM tx_mklog_devlog_entry AS DEVLOGENTRY WHERE 1=1 GROUP BY DEVLOGENTRY.run_id ORDER BY DEVLOGENTRY.run_id DESC LIMIT 50

Ich denke die Abfrage sollte so gestaltet werden, daß sie mit jedem Modus von MySQL funktioniert.

**Comment by digedag** [comment]
Das war es nicht! Der Fehler tritt bei der Abfrage der vorhandenen Extension-Keys auf.

**Comment by rengaw83** [comment]
Der run_id Fehler ist also gelöst.
Die extkey Problematik schau ich mir noch an, bzw. gleich mal alle GROUP BY Statements.
