### ISSUE TITLE
Check size of extradata in bemodule, mail and gelf transports

### ISSUE THREAD

**Issue by rengaw83** [DMKEBUSINESSGMBH/typo3-mklog#7]
The current maximum of extra_data are 16MB.
The BE-Module, E-Mail-Notification and GelfTransports has to check the size of the extra_data and should display a message instead of the large data.
A very large extra_data can be created by [DatabaseConnection::debug_check_recordset()](https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/core/Classes/Database/DatabaseConnection.php#L1872) for example. Ther are the whole backtrace with arguments are stored to the extradata.

- [x] Add a output parser, which can handle the big extradata and creates short messages
- [x] make the maximum of extra_data configurable by extension, log and/or scheduler configuration
- [x] prevent large output of extra_data in BE-Module
- [x] prevent large output of extra_data in E-Mail-Notifications
- [x] prevent large output of extra_data in GelfTransport for direct logs
- [x] prevent large output of extra_data in GelfTransport for scheduled logs

**Comment by rengaw83** [comment]
There is nothing wrong to use the georgringer/logging extension for logging.  
Mklog is a parallel to it, inspired by the old devlog extension.  
The use of monolog would be nice, but a lot of work and you could use georgringer/logging instead.

**Comment by Baachi** [comment]
So what would be the advantage to this extension? Maybe we can add it to the Readme why or better when they should use this extension rather the logging extension from georgringer?

**Comment by rengaw83** [comment]
The georgringer/logging currently is just a concept and only compatible with TYPO3 8. 
To use this we has to use its own monolog manager, instead the devlog or typo3 logger.
This can be very useful for special projects!

Mklog is a generic logging extension, compatible to TYPO3 9, uses the old DevLog-Hook and the new TYPO3-Logger.  
So all logs are included, regardless of whether a extension uses the devlog or the typo3 core loging. No special manager class has to be implemented, just the typo3 core.

Mklog writes all the logs (your own, from the core and all other third party extensions) into the database, apart from critical messages that are sent directly to graylog. Later in the background a scheduler processes the logs (send per mail, or to graylog) to not disturb the frontend request too much.

It is certainly a good idea to port the processes to use the awesome monolog.
But currently this would be too much work.  

I agree that we should include some more information about what mklog really does in the documentation/readme.

**Comment by Baachi** [comment]
Thank you for this clear explanation, now understand this usecase a little bit better.

Just one more question, is the devlog still relevant in favor of the new [logging system](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Logging/Index.html) which is shipped with the core?

**Comment by rengaw83** [comment]
Yes it is.  
A lot of extensions use the old devlog api and it is still part of TYPO3. See [GeneralUtility::devLog](https://github.com/TYPO3/TYPO3.CMS/blob/9.5/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L4029).  
The devlog was removed in TYPO3 10. When we drop the support for TYPO3 9.5, than we should remove the old devlog system.

**Comment by rengaw83** [comment]
New data parser to reduce the size of extra data on watchdog transport (gelf/graylog) was added.  
Release is pending.
